In [6]:
import numpy as np

print("all good")

all good


In [7]:
import numpy as np

# 1. Convert a list of numeric values into a 1D numpy array
numeric_list = [10, 20, 30, 40, 50]
array_1d = np.array(numeric_list)
print(array_1d)

[10 20 30 40 50]


In [8]:
import numpy as np

# 2. Create a 1D array from tuples with float datatype
tuple_data = (1, 2, 3, 4, 5)
float_array_from_tuple = np.array(tuple_data, dtype=float)
print(float_array_from_tuple)

[1. 2. 3. 4. 5.]


In [9]:
import numpy as np

# 3. Convert an array to a float type
int_array = np.array([10, 20, 30])
float_array = int_array.astype(float)
print(float_array)

[10. 20. 30.]


In [10]:
import numpy as np

# 4. Convert a python dictionary to a numpy ndarray
my_dict = {'a': 10, 'b': 20, 'c': 30}

# Option A: Convert dictionary values to array
values_array = np.array(list(my_dict.values()))
print("Values Array:", values_array)

# Option B: Convert dictionary key-value pairs to array
pairs_array = np.array(list(my_dict.items()))
print("Keys & Values Array:\n", pairs_array)

Values Array: [10 20 30]
Keys & Values Array:
 [['a' '10']
 ['b' '20']
 ['c' '30']]
